spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://aevoco-db.c3mac8u4807a.ap-southeast-5.rds.amazonaws.com:5432/testDB
    username: postgres
    password: aevocodb

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
